# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6BoyH1FsWR2GAq7DLLk6ahxsDPmse3e

Práctica Python IE
"""

print("Luis Adrián Fernández Bernal")

print("Luis Adrián Fernández Bernal\n", "Española\n", "Estudiante\n")

x=4
print(x)

y=1
print(y)

string_value = ""
boolean_value = bool(string_value)
print(boolean_value)

bool_val = True
print("Initial value", bool_val)
bool_val = int(bool_val == True)
print("Resultant value", bool_val)

from datetime import date
from datetime import datetime
today = date.today()
now = datetime.now()
print(today)
print(now)

new_date = datetime(1991, 8, 9, 11, 10, 00, 00000)
print(new_date)